### ISSUE TITLE
composer require authing-sdk/php-74 后无法使用

### ISSUE THREAD

**Issue by nirvana72** [Authing/authing-php-sdk#6]
Warning: require_once(/workspace/demo-authing-api/vendor/authing-sdk/php-74/src/../vendor/autoload.php): failed to open stream: No such file or directory in /workspace/demo-authing-api/vendor/authing-sdk/php-74/src/BaseClient.php on line 5

Fatal error: require_once(): Failed opening required '/workspace/demo-authing-api/vendor/authing-sdk/php-74/src/../vendor/autoload.php' (include_path='.:') in /workspace/demo-authing-api/vendor/authing-sdk/php-74/src/BaseClient.php on line 5

~~~
<?php
namespace App\Controller;

use Authing\Mgmt\ManagementClient;

/**
 * @path /
 */
class IndexController
{
    /**
     * @route GET /
     */
    public function index()
    {
        $management = new ManagementClient("********", "********");
        $management->requestToken();

        $users = $management->users()->paginate();

        var_dump($users);
        exit;
    }
}

~~~

**Comment by luojielin** [comment]
感谢您提出的 Issues。
这个问题在 4.2.1 版本里已经做了修复，请尝试升级到新版本。
